# Generated by Django 2.2.4 on 2019-08-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misfa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entryvalue',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
