# Generated by Django 2.2.4 on 2019-08-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misfa', '0002_auto_20190825_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_pushed',
            field=models.BooleanField(default=False),
        ),
    ]
