# Generated by Django 2.2.3 on 2019-07-03 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wajiha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='end_date',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='start_date',
            new_name='start_at',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
