# Generated by Django 2.2.3 on 2019-07-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajiha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
