# Generated by Django 2.2.3 on 2019-07-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajiha', '0002_opportunity_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
