# Generated by Django 2.2.3 on 2019-07-08 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajiha', '0003_auto_20190708_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='wajiha.OpportunityCategory'),
        ),
    ]
