# Generated by Django 2.2.3 on 2019-07-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajiha', '0005_auto_20190708_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
