# Generated by Django 2.2.3 on 2019-07-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajiha', '0006_auto_20190709_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
