# Generated by Django 2.2.3 on 2019-08-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajiha', '0008_opportunity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
