# Generated by Django 2.2.4 on 2019-08-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajiha', '0010_auto_20190820_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
