# Generated by Django 2.2.4 on 2019-08-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajiha', '0011_opportunity_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitycategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
