# Generated by Django 2.2.4 on 2019-08-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajiha', '0012_opportunitycategory_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitycategory',
            name='fontawesome_icon',
            field=models.CharField(default='', max_length=250),
        ),
    ]
