# Generated by Django 2.2.4 on 2019-09-04 15:01

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wajiha', '0013_opportunitycategory_fontawesome_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitycategory',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
