# Generated by Django 2.2.4 on 2019-09-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajiha', '0014_opportunitycategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitycategory',
            name='display_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
