# Generated by Django 2.2.5 on 2019-09-04 19:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wajiha', '0015_opportunitycategory_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
